export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_BY_POST_SUCCESS = 'LOAD_CATEGORIES_BY_POST_SUCCESS';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
